
#
# SPDX-License-Identifier: Apache-2.0
#
---
name: Release Build
on:
  create:
    tags:
      - "v*"
  workflow_dispatch: {}

jobs:

  # Lint, Compile and Core Function Tests
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Use Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install Fabric dependencies
        run: |
          sudo mkdir -p /opt/fabric
          curl -sSL https://github.com/hyperledger/fabric/releases/download/v2.4.6/hyperledger-fabric-linux-amd64-2.4.6.tar.gz | sudo tar xzf - -C /opt/fabric
          curl -sSL https://github.com/hyperledger/fabric-ca/releases/download/v1.5.2/hyperledger-fabric-ca-linux-amd64-1.5.2.tar.gz | sudo tar xzf - -C /opt/fabric
          cd builders/java
          sudo mvn -q dependency:copy-dependencies -DoutputDirectory=/opt/fabric-chaincode-java/lib
          npm install -g fabric-shim@2.4.1
      - name: Run Go formatters and linters
        run: make lint
      - name: Run Go unit tests
        run: make unit
      - name: Run Go integration tests
        run: |
          export PATH="/opt/fabric/bin:${PATH}"
          export FABRIC_CFG_PATH=/opt/fabric/config

          make integration
      - name: Run ShellCheck
        run: shellcheck $(ls builders/*/bin/* -1 | grep -v ccaas)

  # Build the daemon binary and if a release publish if a 'tag' build
  # amd64/arm64
  binary_build:
    name: Binary Build
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        goarch: [amd64, arm64]
    env:
      GOARCH: ${{ matrix.goarch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build Binary
        run: go build -v -o bin/microfabd cmd/microfabd/main.go
      - name: Package Binary
        run: |
          export GOOS=$(go env GOOS)
          tar -C bin -czvf microfab-${GOOS}-${GOARCH}.tgz microfabd
      - name: Publish Binary to GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: microfab-*.tgz
  
  # Build the container images and push to the ghcr.io repo
  # amd64/arm64
  container_build:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      image_digest: ${{ steps.push.outputs.digest }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/hyperledger-labs/microfab
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha,format=long
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile2
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
