
#
# SPDX-License-Identifier: Apache-2.0
#
---
name: CI
on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages
  schedule:
    - cron: "0 0 * * *"
  create:
    tags:
      - "*"
  workflow_dispatch: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Go 1.14
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Use Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install Fabric dependencies
        run: |
          sudo mkdir -p /opt/fabric
          curl -sSL https://github.com/hyperledger/fabric/releases/download/v2.2.2/hyperledger-fabric-linux-amd64-2.2.2.tar.gz | sudo tar xzf - -C /opt/fabric
          curl -sSL https://github.com/hyperledger/fabric-ca/releases/download/v1.4.9/hyperledger-fabric-ca-linux-amd64-1.4.9.tar.gz | sudo tar xzf - -C /opt/fabric
          cd builders/java
          sudo mvn -q dependency:copy-dependencies -DoutputDirectory=/opt/fabric-chaincode-java/lib
          npm install -g fabric-shim@2.2.0
      - name: Run Go formatters and linters
        run: make lint
      - name: Run Go unit tests
        run: make unit
      - name: Run Go integration tests
        run: |
          export PATH="/opt/fabric/bin:${PATH}"
          export FABRIC_CFG_PATH=/opt/fabric/config
          make integration
      - name: Run ShellCheck
        run: shellcheck builders/*/bin/*
      - name: Build Docker image
        run: |
          docker build -t ibmcom/ibp-microfab:latest .
      - name: Publish Docker image to Docker Hub
        env:
            DOCKER_HUB_USER_NAME: ${{ secrets.DOCKER_HUB_USER_NAME }}
            DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          VERSION=$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')
          docker tag ibmcom/ibp-microfab:latest ibmcom/ibp-microfab:${VERSION}
          docker login -u ${DOCKER_HUB_USER_NAME} -p ${DOCKER_HUB_ACCESS_TOKEN}
          docker push ibmcom/ibp-microfab:${VERSION}
          docker push ibmcom/ibp-microfab:latest
        if: startsWith(github.ref, 'refs/tags/')