
#
# SPDX-License-Identifier: Apache-2.0
#
---
name: Pull Request
on:
  pull_request:
  workflow_dispatch: {}

jobs:

  # Lint, Compile and Core Function Tests
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Use Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install Fabric dependencies
        run: |
          sudo mkdir -p /opt/fabric
          curl -sSL https://github.com/hyperledger/fabric/releases/download/v2.4.6/hyperledger-fabric-linux-amd64-2.4.6.tar.gz | sudo tar xzf - -C /opt/fabric
          curl -sSL https://github.com/hyperledger/fabric-ca/releases/download/v1.5.2/hyperledger-fabric-ca-linux-amd64-1.5.2.tar.gz | sudo tar xzf - -C /opt/fabric
          cd builders/java
          sudo mvn -q dependency:copy-dependencies -DoutputDirectory=/opt/fabric-chaincode-java/lib
          npm install -g fabric-shim@2.4.1
      - name: Run Go formatters and linters
        run: make lint
      - name: Run Go unit tests
        run: make unit
      - name: Run Go integration tests
        run: |
          export PATH="/opt/fabric/bin:${PATH}"
          export FABRIC_CFG_PATH=/opt/fabric/config

          make integration
      - name: Run ShellCheck
        run: shellcheck $(ls builders/*/bin/* -1 | grep -v ccaas)
